apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webstore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-health-degraded.msteams-webstore: ""
    notifications.argoproj.io/subscribe.on-sync-failed.msteams-webstore: ""
  labels:
    instance: webstore  
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: webstore-app/overlays/dev
    repoURL: https://github.com/VirtoCommerce/vc-webstore-deploy
    targetRevision: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true